-- ===============================================
-- 소프트룸 & 하드코어룸 가게 및 관리자 등록 SQL
-- ===============================================

-- 1. 가게 등록
INSERT INTO stores (name, address, region, store_type, phone) VALUES
  ('별밤', '', '가락', '하드코어룸', '010-2576-4984'),
  ('올터치', '', '가락', '하드코어룸', '010-5875-7455'),
  ('1%하이쩜오', '', '강남', '소프트룸', ''),
  ('1프로하퍼셔츠 형돈이형', '', '강남', '소프트룸', '010-5691-3584'),
  ('24시 하퍼', '', '강남', '소프트룸', '010-2132-5740'),
  ('24시하이퍼블릭', '', '강남', '소프트룸', '010-8500-2923'),
  ('BAR11CLUB', '', '강남', '소프트룸', '010-4068-1133'),
  ('DOPAMINE수위룸 시우', '', '강남', '소프트룸', '010-2132-9813'),
  ('DOPAMINE터치룸 김태리', '', '강남', '소프트룸', '010-6469-3899'),
  ('IMPACT쩜오', '', '강남', '하드코어룸', ''),
  ('S미러', '', '강남', '하드코어룸', '010-5944-8390'),
  ('가라오케 가격테러범', '', '강남', '소프트룸', '010-9750-5634'),
  ('구구단', '', '강남', '소프트룸', ''),
  ('노아', '', '강남', '소프트룸', ''),
  ('달토', '', '강남', '소프트룸', '010-2177-7235'),
  ('달토터치룸 예쁜연하', '', '강남', '소프트룸', '010-9716-6701'),
  ('더킹', '', '강남', '하드코어룸', '010-6441-4045'),
  ('도파민', '', '강남', '소프트룸', '010-7762-1556'),
  ('두바이퍼블릭', '', '강남', '소프트룸', '010-8698-3529'),
  ('디셈버', '', '강남', '하드코어룸', '010-4231-6966'),
  ('런닝래빗', '', '강남', '소프트룸', ''),
  ('런닝레빗 신동엽', '', '강남', '소프트룸', '010-2373-7223'),
  ('런닝레빗 예쁜안수정', '', '강남', '소프트룸', ''),
  ('레깅스룸', '', '강남', '소프트룸', ''),
  ('룸빵변태 김원훈', '', '강남', '소프트룸', '010-5901-5324'),
  ('룸빵왕 루피대장', '', '강남', '소프트룸', '010-4370-7571'),
  ('매직미러', '', '강남', '하드코어룸', '010-6448-2772'),
  ('매직미러셔츠풀', '', '강남', '하드코어룸', '010-2527-6054'),
  ('매직미러야구장 신세경', '', '강남', '하드코어룸', '010-8406-9646'),
  ('매직미러야구장 전지현', '', '강남', '하드코어룸', '010-7785-7134'),
  ('매직미러풀싸롱 손석구', '', '강남', '하드코어룸', '010-5762-5170'),
  ('매직미러풀싸롱 손예진', '', '강남', '하드코어룸', '010-5813-5170'),
  ('물빨터치룸 과외선생', '', '강남', '소프트룸', '010-4348-7223'),
  ('베리앤굿', '', '강남', '하드코어룸', '010-5939-1509'),
  ('야구장', '', '강남', '하드코어룸', '010-8355-6233'),
  ('야구장매직미러 김연아', '', '강남', '하드코어룸', '010-4885-3541'),
  ('야구장셔츠룸', '', '강남', '소프트룸', '010-8180-7571'),
  ('에덴 용만이', '', '강남', '소프트룸', ''),
  ('엘리트터치룸 이쁜유리', '', '강남', '소프트룸', '010-8399-5819'),
  ('엘리트퍼블릭', '', '강남', '소프트룸', '010-7660-3529'),
  ('연예인급터치룸', '', '강남', '소프트룸', '010-8190-9663'),
  ('올클럽', '', '강남', '하드코어룸', '010-2194-2413'),
  ('유앤미', '', '강남', '소프트룸', '010-4096-8756'),
  ('쩜오구구단 안유진', '', '강남', '소프트룸', ''),
  ('쩜오미친수위 박아연', '', '강남', '소프트룸', ''),
  ('쩜오크크', '', '강남', '소프트룸', ''),
  ('클래식', '', '강남', '소프트룸', '010-7980-7223'),
  ('하드터치룸', '', '강남', '소프트룸', '010-6555-0732'),
  ('하이쩜오', '', '강남', '소프트룸', '010-4348-9902'),
  ('하이쩜오놀이터 홍탁', '', '강남', '소프트룸', ''),
  ('하이터치룸', '', '강남', '소프트룸', '010-6388-6446'),
  ('하이퍼블릭', '', '강남', '소프트룸', ''),
  ('럭셔리셔츠룸 만억이', '', '마포', '소프트룸', '010-7731-7105'),
  ('매직미러레깅스', '', '부산', '하드코어룸', '010-4888-3762'),
  ('매직미러하드풀 백지영', '', '부산', '하드코어룸', '010-9609-7315'),
  ('매직미러한복풀 장원영', '', '부산', '소프트룸', '010-5939-9974'),
  ('멀티비젼초이스', '', '부산', '소프트룸', '010-5756-5835'),
  ('더킹', '', '북창동', '하드코어룸', ''),
  ('발렌시아가', '', '북창동', '하드코어룸', '010-5839-9299'),
  ('드래곤볼', '', '분당', '하드코어룸', ''),
  ('하이퍼블릭', '', '선릉', '소프트룸', ''),
  ('다국적노래클럽', '', '신림', '소프트룸', ''),
  ('풀싸롱', '', '신림', '하드코어룸', ''),
  ('풀클럽', '', '신림', '하드코어룸', ''),
  ('하이퍼블릭', '', '신림', '하드코어룸', ''),
  ('올챙이 해적단', '', '안양', '하드코어룸', ''),
  ('훌러덩', '', '영등포', '하드코어룸', ''),
  ('1등 쓰리노&셔츠룸', '', '인천', '하드코어룸', ''),
  ('유흥총판', '', '일산', '소프트룸', '031-939-0996'),
  ('판도라', '', '일산', '소프트룸', '010-8271-6485'),
  ('하이터치룸', '', '일산', '소프트룸', '010-8386-4070'),
  ('하이퍼블릭 터치룸', '', '장안동', '소프트룸', ''),
  ('티팬티룸', '', '화곡', '하드코어룸', '010-2165-7212');

-- 2. 가상 매니저(관리자) 등록
INSERT INTO virtual_staff (store_id, name) VALUES
  ((SELECT id FROM stores WHERE name = '별밤' AND region = '가락' LIMIT 1), '한별실장'),
  ((SELECT id FROM stores WHERE name = '올터치' AND region = '가락' LIMIT 1), '현아실장'),
  ((SELECT id FROM stores WHERE name = '1%하이쩜오' AND region = '강남' LIMIT 1), '공유대표'),
  ((SELECT id FROM stores WHERE name = '24시 하퍼' AND region = '강남' LIMIT 1), '소지섭대표'),
  ((SELECT id FROM stores WHERE name = '24시하이퍼블릭' AND region = '강남' LIMIT 1), '지예은대표'),
  ((SELECT id FROM stores WHERE name = '24시하이퍼블릭' AND region = '강남' LIMIT 1), '최우식대표'),
  ((SELECT id FROM stores WHERE name = 'BAR11CLUB' AND region = '강남' LIMIT 1), '경호실장'),
  ((SELECT id FROM stores WHERE name = 'IMPACT쩜오' AND region = '강남' LIMIT 1), '우부장'),
  ((SELECT id FROM stores WHERE name = 'S미러' AND region = '강남' LIMIT 1), '장원영실장'),
  ((SELECT id FROM stores WHERE name = '구구단' AND region = '강남' LIMIT 1), '지우마담'),
  ((SELECT id FROM stores WHERE name = '달토' AND region = '강남' LIMIT 1), '봉준대표'),
  ((SELECT id FROM stores WHERE name = '더킹' AND region = '강남' LIMIT 1), '수지실장'),
  ((SELECT id FROM stores WHERE name = '도파민' AND region = '강남' LIMIT 1), '민대표'),
  ((SELECT id FROM stores WHERE name = '도파민' AND region = '강남' LIMIT 1), '짱구이사'),
  ((SELECT id FROM stores WHERE name = '도파민' AND region = '강남' LIMIT 1), '마동석대표'),
  ((SELECT id FROM stores WHERE name = '도파민' AND region = '강남' LIMIT 1), '노홍철사원'),
  ((SELECT id FROM stores WHERE name = '두바이퍼블릭' AND region = '강남' LIMIT 1), '이안여실장'),
  ((SELECT id FROM stores WHERE name = '디셈버' AND region = '강남' LIMIT 1), '정다운대표'),
  ((SELECT id FROM stores WHERE name = '런닝래빗' AND region = '강남' LIMIT 1), '박아영실장'),
  ((SELECT id FROM stores WHERE name = '런닝래빗' AND region = '강남' LIMIT 1), '우지호사장'),
  ((SELECT id FROM stores WHERE name = '레깅스룸' AND region = '강남' LIMIT 1), '이태곤대표'),
  ((SELECT id FROM stores WHERE name = '매직미러' AND region = '강남' LIMIT 1), '박서준이사'),
  ((SELECT id FROM stores WHERE name = '매직미러' AND region = '강남' LIMIT 1), '이정재대표'),
  ((SELECT id FROM stores WHERE name = '매직미러셔츠풀' AND region = '강남' LIMIT 1), '나나실장'),
  ((SELECT id FROM stores WHERE name = '베리앤굿' AND region = '강남' LIMIT 1), '이하니대표'),
  ((SELECT id FROM stores WHERE name = '베리앤굿' AND region = '강남' LIMIT 1), '구영훈대표'),
  ((SELECT id FROM stores WHERE name = '야구장' AND region = '강남' LIMIT 1), '아이유실장'),
  ((SELECT id FROM stores WHERE name = '야구장' AND region = '강남' LIMIT 1), '김다미실장'),
  ((SELECT id FROM stores WHERE name = '야구장셔츠룸' AND region = '강남' LIMIT 1), '차범근대표'),
  ((SELECT id FROM stores WHERE name = '엘리트퍼블릭' AND region = '강남' LIMIT 1), '짱구부장'),
  ((SELECT id FROM stores WHERE name = '엘리트퍼블릭' AND region = '강남' LIMIT 1), '함자영여실장'),
  ((SELECT id FROM stores WHERE name = '연예인급터치룸' AND region = '강남' LIMIT 1), '금강산부장'),
  ((SELECT id FROM stores WHERE name = '올클럽' AND region = '강남' LIMIT 1), '노마진대표'),
  ((SELECT id FROM stores WHERE name = '유앤미' AND region = '강남' LIMIT 1), '하지원대표'),
  ((SELECT id FROM stores WHERE name = '유앤미' AND region = '강남' LIMIT 1), '태수대표'),
  ((SELECT id FROM stores WHERE name = '유앤미' AND region = '강남' LIMIT 1), '카리나실장'),
  ((SELECT id FROM stores WHERE name = '유앤미' AND region = '강남' LIMIT 1), '권지용대표'),
  ((SELECT id FROM stores WHERE name = '쩜오크크' AND region = '강남' LIMIT 1), '고윤정마담'),
  ((SELECT id FROM stores WHERE name = '클래식' AND region = '강남' LIMIT 1), '배대표'),
  ((SELECT id FROM stores WHERE name = '하드터치룸' AND region = '강남' LIMIT 1), '해롱실장'),
  ((SELECT id FROM stores WHERE name = '하이쩜오' AND region = '강남' LIMIT 1), '안대표'),
  ((SELECT id FROM stores WHERE name = '하이터치룸' AND region = '강남' LIMIT 1), '열정범대표'),
  ((SELECT id FROM stores WHERE name = '하이퍼블릭' AND region = '강남' LIMIT 1), '바다대표'),
  ((SELECT id FROM stores WHERE name = '매직미러레깅스' AND region = '부산' LIMIT 1), '하지원실장'),
  ((SELECT id FROM stores WHERE name = '멀티비젼초이스' AND region = '부산' LIMIT 1), '정우대표'),
  ((SELECT id FROM stores WHERE name = '더킹' AND region = '북창동' LIMIT 1), '왕초대표'),
  ((SELECT id FROM stores WHERE name = '발렌시아가' AND region = '북창동' LIMIT 1), '이정재대표'),
  ((SELECT id FROM stores WHERE name = '드래곤볼' AND region = '분당' LIMIT 1), '무다리실장'),
  ((SELECT id FROM stores WHERE name = '하이퍼블릭' AND region = '선릉' LIMIT 1), '예정화실장'),
  ((SELECT id FROM stores WHERE name = '풀싸롱' AND region = '신림' LIMIT 1), '마동석실장'),
  ((SELECT id FROM stores WHERE name = '풀클럽' AND region = '신림' LIMIT 1), '지아실장'),
  ((SELECT id FROM stores WHERE name = '하이퍼블릭' AND region = '신림' LIMIT 1), '주사장'),
  ((SELECT id FROM stores WHERE name = '훌러덩' AND region = '영등포' LIMIT 1), '서부장'),
  ((SELECT id FROM stores WHERE name = '유흥총판' AND region = '일산' LIMIT 1), '입금가부장'),
  ((SELECT id FROM stores WHERE name = '유흥총판' AND region = '일산' LIMIT 1), '김종구부장'),
  ((SELECT id FROM stores WHERE name = '판도라' AND region = '일산' LIMIT 1), '정민사장'),
  ((SELECT id FROM stores WHERE name = '판도라' AND region = '일산' LIMIT 1), '하정실장'),
  ((SELECT id FROM stores WHERE name = '하이터치룸' AND region = '일산' LIMIT 1), '유빈실장'),
  ((SELECT id FROM stores WHERE name = '티팬티룸' AND region = '화곡' LIMIT 1), '마동석사장');

-- 총 가게: 73개 (소프트룸: 45개, 하드코어룸: 28개)
-- 총 관리자: 59명